pc2surfaces:
  max_inner_iter: 35.0
  max_outer_iter: 35.0
  term_perc_crit: 0.07
  normal_dev_thres1: 7.0
  normal_dev_thres2: 3.0
  contour_fit_thres: 0.07
  sphere_r: 5.7
  normal_search_radius: 0.27
  contour_type: "circle"

