visualization:
  plot_pc_orig: true
  plot_pc_sphere: true
  plot_normals: true
  plot_triads: true
  plot_planes: true
  plot_segments: true
  plot_cylinders: true
  enable_pcl_viewer: false
  pc_orig_color:
    r: 1.0
    g: 1.0
    b: 1.0
    a: 0.3
  pc_sphere_color:
    r: 1.0
    g: 0.3
    b: 0.3
    a: 0.3
  normals_color:
    r: 1.0
    g: 0.3
    b: 0.0
    a: 0.8
  cylinders_alpha: 0.9
  cylinders_line_scale: 0.05
  cylinders_resolution: 30
  normals_scale: 0.03
  normals_norm: 0.45
  normals_skip: 1
  triads_scale: 0.05
  triads_norm: 0.75
  planes_scale: 6.50


