alpha: 0.4
beta:  2.0
kappa: 0.0

noise_std:
  process:
    acc:
      x: 0.2
      y: 0.2
      z: 0.2
    w:
      x: 0.1
      y: 0.1
      z: 0.1
    acc_bias:
      x: 0.02
      y: 0.02
      z: 0.02
    att_bias:
      pitch: 0.000005
      roll:  0.000005
